version: '3.1'

services:

  app_api_geteway:
    image: '840456e69594'
    container_name: spring_application_api_geteway
    ports:
      - '127.0.0.1:8091:8091'

  app:
    image: '88393ee5c8f9'
    container_name: spring_application
    ports:
      - '127.0.0.1:8189:8189'
    environment:
      - DB_USER=pavel
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  billservice_app:
    image: 'e6692c05cb52'
    container_name: spring_application_billservice
    ports:
      - '127.0.0.1:8190:8190'
    environment:
      - DB_USER=pavel
      - DB_URL=jdbc:postgresql://db:5432/billservicelab_db
      - DB_PASSWORD=password
    depends_on:
      - db

  app_userservice:
    image: '54dfa6620a5e'
    container_name: spring_application_userservice
    ports:
      - '127.0.0.1:8191:8191'
    environment:
      - DB_USER=pavel
      - DB_URL=jdbc:postgresql://db:5432/userservice_db
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=pavel
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: